name: Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger when you push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Log in to Amazon ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin 718881314280.dkr.ecr.us-east-1.amazonaws.com

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t tennis-equipment-manager .

      # Step 5: Tag Docker image for ECR
      - name: Tag Docker image
        run: |
          docker tag tennis-equipment-manager:latest \
          718881314280.dkr.ecr.us-east-1.amazonaws.com/racquet-app:latest

      # Step 6: Push Docker image to ECR
      - name: Push Docker image
        run: |
          docker push 718881314280.dkr.ecr.us-east-1.amazonaws.com/racquet-app:latest
